services:
  app:
    build:
      context: ./backend-ecommerce-laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend-ecommerce-laravel:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
